# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f42972df7feb6c43f1a7eac54a10d35ce44baa016ee17ba7174ca6df6ca3aa2ca498adc543b63034c3f1ded37718acea9253b5bc380c5ba9a0d58fa82d15743

test:
  secret_key_base: c1431c873d8afa6abfa53572cbb7029e89525ddf44af5fdee548bf8d25fdd7e80d7ff9f340c7d1578c9c95bd14a44490033cb2d460d3bb838f5ed87cb627dce7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
